

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    networks:
      - smartcampus-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - smartcampus-network

networks:
  smartcampus-network:
    driver: bridge
